#-----------DEFAULT CODES-------------------
NO_ERROR = 1
ERROR_THREAD_PROCESS_TIMEOUT = -1

#-----------WIFI ERROR CODES----------------
ERROR_CONNECTING_TO_INTERNET = -11
ERROR_CONNECTING_TO_WIFI = -12
ERROR_TURNING_WIFI_OFF = -13
ERROR_FETCHING_WIFI_LIST = -14
ERROR_FETCHING_SSID = -15
ERROR_TURNING_WIFI_ON = -16
ERROR_WIFI_NOT_CONNECTED_TO_NETWORK = -17




ERROR_CODE_ROLLBACK_PKG_NOT_AVAILABLE = -20
ERROR_CODE_FAILED_TO_GET_NEW_UPDATE = -21
ERROR_CODE_PKG_DOWNLOAD_FAILED = -22
ERROR_CODE_PKG_NO_UPDATE_AVAILABLE = -23
ERROR_CODE_INVALID_JSON = -24


ERROR_CODE_NO_PACKAGE_AVAILABLE = -25

#------------------Dashboard backend error codes---------------------------
ERROR_UNKNOWN_DASBOARD_ERROR = -100
ERROR_INVALID_RESPONSE_OBJECT = -101
ERROR_MACHINE_UDI_ALREADY_REGISTERED = -102
ERROR_SYSTEM_NUM_MUST_BE_UNIQUE = -103
ERROR_UPDATE_MACHINE_VERSION = -104
ERROR_MACHINE_NOT_REGISTERED = -105
ERROR_SYSTEM_VERSION_ALREADY_EXISTS = -106
ERROR_MACHINE_ALREADY_UPDATED = -107
ERROR_REQ_DATA_NOT_PROVIDED_IN_RESP_BODY = -108
ERROR_INTERNAL_DASHBOARD_BACKEND = -109

ERROR_CODES_MAP_DASHBOARD = {
                             601: ERROR_MACHINE_UDI_ALREADY_REGISTERED,
                             602: ERROR_SYSTEM_NUM_MUST_BE_UNIQUE,
                             603: ERROR_UPDATE_MACHINE_VERSION,
                             604: ERROR_MACHINE_NOT_REGISTERED,
                             605: ERROR_SYSTEM_VERSION_ALREADY_EXISTS,
                             606: ERROR_MACHINE_ALREADY_UPDATED,
                             400: ERROR_REQ_DATA_NOT_PROVIDED_IN_RESP_BODY,
                             500: ERROR_INTERNAL_DASHBOARD_BACKEND
                            }

#---------------------File operation errors-----------------------------------
ERROR_FILE_READ_WRITE_FAILED = -150

#---------------------s3 bucket errors-----------------------------------
ERROR_DOWNLOADING_PACKAGE = -200